'use strict'

try{
  x = 10;   
}catch(e){
  console.log(e);
}finally{ //OPCIONAL
    console.log("Se ejecuta siempre al finalizar la revisi칩n del try-catch");
}

console.log("Gracias al try-catch el programa no termina su ejecuci칩n y se continua con la ejecuci칩n del programa, adem치s de que se muestra el error en la consola");